version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: develop
