name: Post-Release Sync

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  main-to-develop-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: develop

      - name: Reset main branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Create PR from main to develop
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge main into develop"
          body: "This PR merges changes from main into develop."
          branch: sync-main-to-develop
          delete-branch: true
