name: Post-Release Sync

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: read

jobs:
  main-to-develop-sync:
    permissions:
      contents: write  # for git push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "joltbot"
          git config user.email "joltbot@users.noreply.github.com"

      - name: Merge main into develop
        run: |
          git fetch origin develop
          git checkout develop
          git merge main --no-ff --allow-unrelated-histories
          git push origin develop
