name: Pre-Release Sync

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: read

jobs:
  develop-to-master-sync:
    permissions:
      contents: write  # for git push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: develop

      - name: Configure Git
        run: |
          git config user.name "joltbot"
          git config user.email "joltbot@users.noreply.github.com"

      - name: Merge develop into master
        run: |
          git fetch origin master
          git checkout master
          git merge develop --no-ff --allow-unrelated-histories
          git push origin master
