name: Auto Publish to Maven Central

on:
  release:
    types: [published] # Trigger on release publish

permissions:
  contents: read # Required for reading the repository contents
  packages: write # Required for publishing packages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Cache OWASP Dependency-Check data
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check-data-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            dependency-check-data-${{ runner.os }}-
      - name: Set up Maven Central Repository
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests -DperformRelease=true -Dnvd.api.key=${{ secrets.NVD_API_KEY }}
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }} # Optional, if needed for NVD checks
